/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIOverview: typeof import('./src/components/AIOverview.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DefaultArticle: typeof import('./src/components/articles/DefaultArticle.vue')['default']
    GoogleArticle: typeof import('./src/components/articles/GoogleArticle.vue')['default']
    GoogleChinaArticle: typeof import('./src/components/articles/GoogleChinaArticle.vue')['default']
    GoogleChinaBlockArticle: typeof import('./src/components/articles/GoogleChinaBlockArticle.vue')['default']
    GoogleChinaEnterArticle: typeof import('./src/components/articles/GoogleChinaEnterArticle.vue')['default']
    GoogleChinaInfluenceArticle: typeof import('./src/components/articles/GoogleChinaInfluenceArticle.vue')['default']
    GoogleChinaQuitArticle: typeof import('./src/components/articles/GoogleChinaQuitArticle.vue')['default']
    GoogleChinaRelationsArticle: typeof import('./src/components/articles/GoogleChinaRelationsArticle.vue')['default']
    GoogleChinaRetrospectiveArticle: typeof import('./src/components/articles/GoogleChinaRetrospectiveArticle.vue')['default']
    GoogleFooter: typeof import('./src/components/GoogleFooter.vue')['default']
    GoogleHeader: typeof import('./src/components/GoogleHeader.vue')['default']
    GoogleSearch: typeof import('./src/components/GoogleSearch.vue')['default']
    GoogleTieba: typeof import('./src/components/articles/GoogleTieba.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/SearchResult.vue')['default']
    SearchSuggestions: typeof import('./src/components/SearchSuggestions.vue')['default']
  }
}
